import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { AlertCard } from '../../components/common/AlertCard';
import { RiskLevel } from '../../types';
import { AlertTriangle, Filter, CheckCircle2, ShieldAlert } from 'lucide-react';
import { EmptyState } from '../../components/common/FeedbackStates';

export const CitizenAlerts: React.FC = () => {
  const { alerts, navigate, setSelectedZone } = useApp();
  const [activeFilter, setActiveFilter] = useState<'all' | RiskLevel | 'resolved'>('all');

  const filteredAlerts = alerts.filter((alert) => {
    if (activeFilter === 'all') return alert.status !== 'resolved';
    if (activeFilter === 'resolved') return alert.status === 'resolved';
    return alert.severity === activeFilter && alert.status !== 'resolved';
  });

  const handleViewOnMap = (zoneId: string) => {
    navigate('/citizen/map');
  };

  const counts = {
    all: alerts.filter(a => a.status !== 'resolved').length,
    critical: alerts.filter(a => a.severity === 'critical' && a.status !== 'resolved').length,
    high: alerts.filter(a => a.severity === 'high' && a.status !== 'resolved').length,
    moderate: alerts.filter(a => a.severity === 'moderate' && a.status !== 'resolved').length,
    resolved: alerts.filter(a => a.status === 'resolved').length,
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="border-b border-white/5 pb-4 flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-semibold text-rose-400">
            <ShieldAlert className="h-4 w-4" />
            <span>Emergency Public Broadcasts</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white mt-1">
            Alerts & Warnings
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 mt-1">
            Official hydraulic warnings generated by coupled radar-drainage nowcasting engine.
          </p>
        </div>

        <div className="flex items-center gap-2 rounded-xl bg-command-900 px-3.5 py-2 border border-white/10 text-xs font-mono">
          <span className="text-slate-400">Active Warnings:</span>
          <span className="font-bold text-rose-400">{counts.all}</span>
        </div>
      </div>

      {/* Filter Buttons */}
      <div className="flex flex-wrap items-center gap-2 pb-2">
        <button
          onClick={() => setActiveFilter('all')}
          className={`rounded-xl px-4 py-2 text-xs font-semibold transition-all ${
            activeFilter === 'all'
              ? 'bg-cyan-600 text-white shadow-sm'
              : 'bg-command-900 text-slate-400 hover:text-white border border-white/5'
          }`}
        >
          All Active ({counts.all})
        </button>

        <button
          onClick={() => setActiveFilter('critical')}
          className={`rounded-xl px-4 py-2 text-xs font-semibold transition-all ${
            activeFilter === 'critical'
              ? 'bg-rose-600 text-white shadow-sm'
              : 'bg-command-900 text-rose-400 hover:bg-rose-950/40 border border-rose-500/20'
          }`}
        >
          🔴 Critical ({counts.critical})
        </button>

        <button
          onClick={() => setActiveFilter('high')}
          className={`rounded-xl px-4 py-2 text-xs font-semibold transition-all ${
            activeFilter === 'high'
              ? 'bg-orange-600 text-white shadow-sm'
              : 'bg-command-900 text-orange-400 hover:bg-orange-950/40 border border-orange-500/20'
          }`}
        >
          🟠 High ({counts.high})
        </button>

        <button
          onClick={() => setActiveFilter('moderate')}
          className={`rounded-xl px-4 py-2 text-xs font-semibold transition-all ${
            activeFilter === 'moderate'
              ? 'bg-amber-600 text-white shadow-sm'
              : 'bg-command-900 text-amber-400 hover:bg-amber-950/40 border border-amber-500/20'
          }`}
        >
          🟡 Moderate ({counts.moderate})
        </button>

        <button
          onClick={() => setActiveFilter('resolved')}
          className={`rounded-xl px-4 py-2 text-xs font-semibold transition-all ${
            activeFilter === 'resolved'
              ? 'bg-emerald-600 text-white shadow-sm'
              : 'bg-command-900 text-emerald-400 hover:bg-emerald-950/40 border border-emerald-500/20'
          }`}
        >
          🟢 Resolved ({counts.resolved})
        </button>
      </div>

      {/* Alerts Cards List */}
      {filteredAlerts.length > 0 ? (
        <div className="space-y-4">
          {filteredAlerts.map((alert) => (
            <AlertCard
              key={alert.id}
              alert={alert}
              onViewOnMap={handleViewOnMap}
              isAuthorityView={false}
            />
          ))}
        </div>
      ) : (
        <EmptyState
          title="No Alerts Found"
          description={`There are currently no ${activeFilter} warnings in the Chennai metropolitan area.`}
          actionLabel="Show All Active Alerts"
          onAction={() => setActiveFilter('all')}
        />
      )}
    </div>
  );
};
